name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Package artifact
        run: npm run package

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: cz-excel-copilot
          path: |
            release/*.zip
